#!/usr/bin/env bash
#
# install-service.sh - Install pi500kb binary, hook script, and systemd service
#
# AI generated by GitHub Copilot v1.0
# End of AI generated code

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BINARY="${SCRIPT_DIR}/build/pi500kb"
HOOK_SRC="${SCRIPT_DIR}/hook.sh"
SERVICE_SRC="${SCRIPT_DIR}/pi500kb.service"

BIN_DST="/usr/local/bin/pi500kb"
HOOK_DIR="/usr/share/pi500kb"
HOOK_DST="${HOOK_DIR}/hook.sh"
SERVICE_DST="/etc/systemd/system/pi500kb.service"

# Check prerequisites
if [ ! -f "${BINARY}" ]; then
    echo "Error: Binary not found at ${BINARY}"
    echo "Run ./make.sh first to build the project."
    exit 1
fi

if [ ! -f "${HOOK_SRC}" ]; then
    echo "Error: hook.sh not found at ${HOOK_SRC}"
    exit 1
fi

# --- Install binary ---
echo "Installing binary to ${BIN_DST}..."
install -Dm755 "${BINARY}" "${BIN_DST}"

# --- Install hook script ---
echo "Installing hook script to ${HOOK_DST}..."
install -Dm755 "${HOOK_SRC}" "${HOOK_DST}"

# --- Generate systemd service file ---
echo "Installing systemd service to ${SERVICE_DST}..."
cat > "${SERVICE_DST}" <<- SERVICE
[Unit]
Description=pi500kb USB OTG Keyboard & Mouse forwarding
Documentation=https://github.com/martins/pi500kb
After=multi-user.target

[Service]
ExecStart=${BIN_DST} --hook-path ${HOOK_DST}
User=root
Group=root
Type=simple
Restart=on-failure

[Install]
WantedBy=multi-user.target
SERVICE

# --- Reload systemd and enable service ---
echo "Reloading systemd daemon..."
systemctl daemon-reload

echo "Enabling pi500kb service (starts on boot)..."
systemctl enable pi500kb

echo "Starting pi500kb service..."
systemctl start pi500kb

echo ""
echo "Installation complete!"
echo "  Binary:      ${BIN_DST}"
echo "  Hook script: ${HOOK_DST}"
echo "  Service:     ${SERVICE_DST}"
echo ""
echo "Status:"
systemctl status pi500kb --no-pager 2>&1 || true
