#!/usr/bin/env bash
#
# install.sh - Install the pi500kb binary to a specified location
#
# Usage: ./install.sh [destination]
#   destination - Install path (default: /usr/local/bin/pi500kb)
#
# AI generated by GitHub Copilot v1.0

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BINARY="${SCRIPT_DIR}/build/pi500kb"
DEFAULT_DST="/usr/local/bin/pi500kb"
DEST="${1:-${DEFAULT_DST}}"

# Show usage if --help or -h
if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
    echo "Usage: $(basename "$0") [destination]"
    echo ""
    echo "Install the pi500kb binary to the specified location."
    echo ""
    echo "Arguments:"
    echo "  destination    Install path (default: ${DEFAULT_DST})"
    echo ""
    echo "Examples:"
    echo "  $(basename "$0")                     # Install to ${DEFAULT_DST}"
    echo "  $(basename "$0") ~/bin/pi500kb       # Install to user's ~/bin"
    exit 0
fi

# Check prerequisites
if [ ! -f "${BINARY}" ]; then
    echo "Error: Binary not found at ${BINARY}"
    echo "Run ./make.sh first to build the project."
    exit 1
fi

# Install binary
echo "Installing pi500kb to ${DEST}..."
install -Dm755 "${BINARY}" "${DEST}"
echo "Done."
# End of AI generated code
