/*
 * AI generated by GitHub Copilot - DeepSeek V4 Flash
 *
 * keyqueue.cc — Thread-safe key event queue for keyboard macro/mapping support.
 */
#include "keyqueue.h"

#include <cstring>

/*
 * AI generated by GitHub Copilot - DeepSeek V4 Flash
 *
 * Default key mapping table (identity = pass-through).
 * Override entries to remap keycodes, e.g.:
 *   keycode_map[0x...] = 0x...;  // Italian → German mapping
 */
uint8_t keycode_map[256] = {0};
/* End of AI generated block */


/*
 * AI generated by GitHub Copilot - DeepSeek V4 Flash
 *
 * KeyQueue implementation
 */
void KeyQueue::push(const KeyEvent& ev) {
    std::lock_guard<std::mutex> lock(mutex_);
    queue_.push(ev);
}

bool KeyQueue::pop(KeyEvent& ev) {
    std::lock_guard<std::mutex> lock(mutex_);
    if (queue_.empty()) return false;
    ev = queue_.front();
    queue_.pop();
    return true;
}

void KeyQueue::clear() {
    std::lock_guard<std::mutex> lock(mutex_);
    while (!queue_.empty()) queue_.pop();
}

bool KeyQueue::empty() const {
    std::lock_guard<std::mutex> lock(mutex_);
    return queue_.empty();
}

size_t KeyQueue::size() const {
    std::lock_guard<std::mutex> lock(mutex_);
    return queue_.size();
}
/* End of AI generated block */


/*
 * AI generated by GitHub Copilot - DeepSeek V4 Flash
 *
 * Diff two HID reports to find which keys were pressed or released.
 * Pushes individual KeyEvents into the provided queue.
 */
void diff_hid_reports(const unsigned char* old_report,
                      const unsigned char* new_report,
                      KeyQueue& queue) {
    // Modifier byte (byte 0): XOR to find changed modifiers
    uint8_t old_mod = old_report[0];
    uint8_t new_mod = new_report[0];
    uint8_t changed_mod = old_mod ^ new_mod;

    // Report changed modifiers as individual keys
    // Modifier bits: Ctrl=0x01, Shift=0x02, Alt=0x04, GUI=0x08
    static const uint8_t mod_bits[] = {0x01, 0x02, 0x04, 0x08};
    static const uint8_t mod_codes[] = {
        0xE0,  // Left Ctrl
        0xE1,  // Left Shift
        0xE2,  // Left Alt
        0xE3   // Left GUI
    };
    for (int i = 0; i < 4; i++) {
        if (changed_mod & mod_bits[i]) {
            KeyEvent ev;
            ev.modifiers = new_mod;
            ev.keycode = mod_codes[i];
            ev.pressed = (new_mod & mod_bits[i]) != 0;
            queue.push(ev);
        }
    }

    // Keycode bytes (bytes 2..7): find what appeared or disappeared
    // Collect keys currently in old and new reports
    bool old_keys[256] = {false};
    bool new_keys[256] = {false};

    for (int i = 2; i < KEYBOARD_HID_REPORT_SIZE; i++) {
        if (old_report[i] != 0) old_keys[old_report[i]] = true;
        if (new_report[i] != 0) new_keys[new_report[i]] = true;
    }

    // Keys released: present in old but not in new
    for (int i = 2; i < KEYBOARD_HID_REPORT_SIZE; i++) {
        uint8_t k = old_report[i];
        if (k != 0 && !new_keys[k]) {
            KeyEvent ev;
            ev.modifiers = new_mod;
            ev.keycode = k;
            ev.pressed = false;
            queue.push(ev);
        }
    }

    // Keys pressed: present in new but not in old
    for (int i = 2; i < KEYBOARD_HID_REPORT_SIZE; i++) {
        uint8_t k = new_report[i];
        if (k != 0 && !old_keys[k]) {
            KeyEvent ev;
            ev.modifiers = new_mod;
            ev.keycode = k;
            ev.pressed = true;
            queue.push(ev);
        }
    }
}
/* End of AI generated block */


/*
 * AI generated by GitHub Copilot - DeepSeek V4 Flash
 *
 * Build a modifier byte from held modifier keys.
 * Modifier keycodes are in range 0xE0-0xE7.
 */
uint8_t modifiers_from_held(const bool held_keys[256]) {
    uint8_t mod = 0;
    if (held_keys[0xE0]) mod |= 0x01;  // Left Ctrl
    if (held_keys[0xE1]) mod |= 0x02;  // Left Shift
    if (held_keys[0xE2]) mod |= 0x04;  // Left Alt
    if (held_keys[0xE3]) mod |= 0x08;  // Left GUI
    if (held_keys[0xE4]) mod |= 0x10;  // Right Ctrl
    if (held_keys[0xE5]) mod |= 0x20;  // Right Shift
    if (held_keys[0xE6]) mod |= 0x40;  // Right Alt
    if (held_keys[0xE7]) mod |= 0x80;  // Right GUI
    return mod;
}
/* End of AI generated block */


/*
 * AI generated by GitHub Copilot - DeepSeek V4 Flash
 *
 * Process a queue of KeyEvents into an output HID report.
 * Applies keycode_map remapping.
 *
 * Returns the final report in out_report (8 bytes).
 */
void process_key_queue(KeyQueue& queue,
                       unsigned char* out_report,
                       bool is_grabbed) {
    // Start with empty report
    memset(out_report, 0, KEYBOARD_HID_REPORT_SIZE);

    KeyEvent ev;
    //
    // TODO: In future, intercept and remap keycodes here using
    //       keycode_map before building the output report.
    //       For Italian → German layout simulation, populate
    //       keycode_map with the desired HID code substitutions.
    //

    // Track currently-pressed keys (including modifiers)
    bool held_keys[256] = {false};

    while (queue.pop(ev)) {
        uint8_t mapped = keycode_map[ev.keycode];
        uint8_t effective_key = (mapped != 0) ? mapped : ev.keycode;

        if (ev.pressed) {
            held_keys[effective_key] = true;
        } else {
            held_keys[effective_key] = false;
        }
    }

    // Build output report from held keys
    out_report[0] = modifiers_from_held(held_keys);

    // Write held non-modifier keycodes (up to 6)
    int key_idx = 2;
    for (int h = 4; h < 256; h++) {
        if (held_keys[h]) {
            // Skip modifier keycodes — they go in byte 0
            if (h >= 0xE0 && h <= 0xE7) continue;
            out_report[key_idx++] = static_cast<uint8_t>(h);
            held_keys[h] = false;  // consume
            if (key_idx >= 8) break;
        }
    }
}
/* End of AI generated block */
