/*
 * AI generated by GitHub Copilot - DeepSeek V4 Flash
 *
 * keyqueue.cc — Thread-safe key event queue for keyboard macro/mapping support.
 */
#include "keyqueue.h"

#include <cstring>
#include <cerrno>
#include <unistd.h>
#include <vector>
#include <fstream>
#include <iostream>

#include <nlohmann/json.hpp>

using json = nlohmann::json;

/*
 * AI generated by GitHub Copilot - DeepSeek V4 Flash
 *
 * Default key mapping table (identity = pass-through).
 * Override entries to remap keycodes, e.g.:
 *   keycode_map[0x...] = 0x...;  // Italian → German mapping
 */
uint8_t keycode_map[256] = {0};
/* End of AI generated block */


/*
 * AI generated by GitHub Copilot - DeepSeek V4 Flash
 *
 * KeyQueue implementation
 */
void KeyQueue::push(const KeyEvent& ev) {
    std::lock_guard<std::mutex> lock(mutex_);
    queue_.push(ev);
}

bool KeyQueue::pop(KeyEvent& ev) {
    std::lock_guard<std::mutex> lock(mutex_);
    if (queue_.empty()) return false;
    ev = queue_.front();
    queue_.pop();
    return true;
}

void KeyQueue::clear() {
    std::lock_guard<std::mutex> lock(mutex_);
    while (!queue_.empty()) queue_.pop();
}

bool KeyQueue::empty() const {
    std::lock_guard<std::mutex> lock(mutex_);
    return queue_.empty();
}

size_t KeyQueue::size() const {
    std::lock_guard<std::mutex> lock(mutex_);
    return queue_.size();
}
/* End of AI generated block */


/*
 * AI generated by GitHub Copilot - DeepSeek V4 Flash
 *
 * Diff two HID reports to find which keys were pressed or released.
 * Pushes individual KeyEvents into the provided queue.
 */
void diff_hid_reports(const unsigned char* old_report,
                      const unsigned char* new_report,
                      KeyQueue& queue) {
    // Modifier byte (byte 0): XOR to find changed modifiers
    uint8_t old_mod = old_report[0];
    uint8_t new_mod = new_report[0];
    uint8_t changed_mod = old_mod ^ new_mod;

    // Report changed modifiers as individual keys
    // Modifier bits: Ctrl=0x01, Shift=0x02, Alt=0x04, GUI=0x08
    static const uint8_t mod_bits[] = {0x01, 0x02, 0x04, 0x08};
    static const uint8_t mod_codes[] = {
        0xE0,  // Left Ctrl
        0xE1,  // Left Shift
        0xE2,  // Left Alt
        0xE3   // Left GUI
    };
    for (int i = 0; i < 4; i++) {
        if (changed_mod & mod_bits[i]) {
            KeyEvent ev;
            ev.modifiers = new_mod;
            ev.keycode = mod_codes[i];
            ev.pressed = (new_mod & mod_bits[i]) != 0;
            queue.push(ev);
        }
    }

    // Keycode bytes (bytes 2..7): find what appeared or disappeared
    // Collect keys currently in old and new reports
    bool old_keys[256] = {false};
    bool new_keys[256] = {false};

    for (int i = 2; i < KEYBOARD_HID_REPORT_SIZE; i++) {
        if (old_report[i] != 0) old_keys[old_report[i]] = true;
        if (new_report[i] != 0) new_keys[new_report[i]] = true;
    }

    // Keys released: present in old but not in new
    for (int i = 2; i < KEYBOARD_HID_REPORT_SIZE; i++) {
        uint8_t k = old_report[i];
        if (k != 0 && !new_keys[k]) {
            KeyEvent ev;
            ev.modifiers = new_mod;
            ev.keycode = k;
            ev.pressed = false;
            queue.push(ev);
        }
    }

    // Keys pressed: present in new but not in old
    for (int i = 2; i < KEYBOARD_HID_REPORT_SIZE; i++) {
        uint8_t k = new_report[i];
        if (k != 0 && !old_keys[k]) {
            KeyEvent ev;
            ev.modifiers = new_mod;
            ev.keycode = k;
            ev.pressed = true;
            queue.push(ev);
        }
    }
}
/* End of AI generated block */


/*
 * AI generated by GitHub Copilot - DeepSeek V4 Flash
 *
 * Build a modifier byte from held modifier keys.
 * Modifier keycodes are in range 0xE0-0xE7.
 */
uint8_t modifiers_from_held(const bool held_keys[256]) {
    uint8_t mod = 0;
    if (held_keys[0xE0]) mod |= 0x01;  // Left Ctrl
    if (held_keys[0xE1]) mod |= 0x02;  // Left Shift
    if (held_keys[0xE2]) mod |= 0x04;  // Left Alt
    if (held_keys[0xE3]) mod |= 0x08;  // Left GUI
    if (held_keys[0xE4]) mod |= 0x10;  // Right Ctrl
    if (held_keys[0xE5]) mod |= 0x20;  // Right Shift
    if (held_keys[0xE6]) mod |= 0x40;  // Right Alt
    if (held_keys[0xE7]) mod |= 0x80;  // Right GUI
    return mod;
}
/* End of AI generated block */


/*
 * AI generated by GitHub Copilot - DeepSeek V4 Flash
 *
 * Process a queue of KeyEvents into an output HID report.
 * Applies keycode_map remapping.
 *
 * Returns the final report in out_report (8 bytes).
 */
void process_key_queue(KeyQueue& queue,
                       unsigned char* out_report,
                       bool is_grabbed) {
    // Start with empty report
    memset(out_report, 0, KEYBOARD_HID_REPORT_SIZE);

    KeyEvent ev;
    //
    // TODO: In future, intercept and remap keycodes here using
    //       keycode_map before building the output report.
    //       For Italian → German layout simulation, populate
    //       keycode_map with the desired HID code substitutions.
    //

    // Track currently-pressed keys (including modifiers)
    bool held_keys[256] = {false};

    while (queue.pop(ev)) {
        uint8_t mapped = keycode_map[ev.keycode];
        uint8_t effective_key = (mapped != 0) ? mapped : ev.keycode;

        if (ev.pressed) {
            held_keys[effective_key] = true;
        } else {
            held_keys[effective_key] = false;
        }
    }

    // Build output report from held keys
    out_report[0] = modifiers_from_held(held_keys);

    // Write held non-modifier keycodes (up to 6)
    int key_idx = 2;
    for (int h = 4; h < 256; h++) {
        if (held_keys[h]) {
            // Skip modifier keycodes — they go in byte 0
            if (h >= 0xE0 && h <= 0xE7) continue;
            out_report[key_idx++] = static_cast<uint8_t>(h);
            held_keys[h] = false;  // consume
            if (key_idx >= 8) break;
        }
    }
}
/* End of AI generated block */


/*
 * AI generated by GitHub Copilot - DeepSeek V4 Flash
 *
 * Macro table — dynamic vector of key-sequence macro definitions.
 */
std::vector<Macro> macros;
/* End of AI generated block */


/*
 * AI generated by GitHub Copilot - DeepSeek V4 Flash
 *
 * Add a macro definition to the table.
 * Returns the index, or -1 on failure.
 */
int add_macro(uint8_t trigger_mod, uint8_t trigger_key, uint8_t mod_mask,
              std::vector<MacroStep> steps) {
    Macro m;
    m.trigger_mod = trigger_mod;
    m.trigger_key = trigger_key;
    m.mod_mask = mod_mask;
    m.steps = std::move(steps);
    macros.push_back(std::move(m));
    return static_cast<int>(macros.size()) - 1;
}
/* End of AI generated block */


/*
 * AI generated by GitHub Copilot - DeepSeek V4 Flash
 *
 * Check raw HID reports for macro triggers and execute if matched.
 *
 * A macro triggers when:
 *   - A specific key is newly pressed (was absent in old_report,
 *     present in new_report)
 *   - While specific modifier bits are held (checked via mod_mask)
 *
 * When triggered, the macro's step sequence is written to hid_output_fd
 * as a series of HID reports (report_id=1). The caller should skip
 * normal forwarding of this report.
 *
 * Returns true if a macro was executed.
 */
bool check_and_execute_macro(const unsigned char* old_report,
                              const unsigned char* new_report,
                              int hid_output_fd) {
    uint8_t new_mod = new_report[0];

    // Collect keys that are NEWLY pressed (in new_report but not old_report)
    uint8_t new_keys[6];
    int new_count = 0;

    for (int i = 2; i < KEYBOARD_HID_REPORT_SIZE; i++) {
        uint8_t k = new_report[i];
        if (k == 0) continue;
        bool was_in_old = false;
        for (int j = 2; j < KEYBOARD_HID_REPORT_SIZE; j++) {
            if (old_report[j] == k) { was_in_old = true; break; }
        }
        if (!was_in_old) {
            if (new_count < 6) new_keys[new_count++] = k;
        }
    }

    // Also detect modifier-bit changes (e.g. a modifier key just pressed)
    uint8_t old_mod = old_report[0];
    uint8_t new_mod_bits = new_mod & ~old_mod;  // bits just turned on

    // Check each macro
    for (const auto& macro : macros) {
        // Check modifier mask match
        if ((new_mod & macro.mod_mask) != (macro.trigger_mod & macro.mod_mask))
            continue;

        // For keycode trigger: check if trigger_key was newly pressed
        if (macro.trigger_key != 0) {
            bool found = false;
            for (int i = 0; i < new_count; i++) {
                if (new_keys[i] == macro.trigger_key) {
                    found = true;
                    break;
                }
            }
            if (!found) continue;
        }

        // Macro triggered! Write the step sequence to HID output.
        // Format: [report_id=1] [modifier] [reserved=0] [6 keycodes]
        unsigned char hid_report[KEYBOARD_HID_REPORT_SIZE + 1];
        hid_report[0] = 1;  // report_id

        for (const auto& step : macro.steps) {
            memset(hid_report + 1, 0, KEYBOARD_HID_REPORT_SIZE);
            hid_report[1] = step.modifier;  // byte 1 = modifier
            // byte 2 is reserved (0x00)
            memcpy(hid_report + 3, step.keys, 6);  // bytes 3-8
            // Retry on EAGAIN — USB endpoint may be busy
            int retries = 50;
            while (retries-- > 0) {
                ssize_t wr = write(hid_output_fd, hid_report,
                                   KEYBOARD_HID_REPORT_SIZE + 1);
                if (wr >= 0) break;
                if (errno == EAGAIN) {
                    usleep(1000);  // 1ms, then retry
                } else {
                    break;  // real error, give up
                }
            }
            if (step.delay_us > 0) {
                usleep(step.delay_us);
            }
        }

        return true;
    }

    return false;
}
/* End of AI generated block */


/*
 * AI generated by GitHub Copilot - DeepSeek V4 Flash
 *
 * JSON config file loader for keyboard layouts.
 *
 * Expected JSON format:
 * {
 *   "language": "Italian",
 *   "description": "...",
 *   "host_os": "windows",       // optional, for documentation
 *   "keycode_map": {            // optional, key remapping
 *     "44": "44",               // "from_code": "to_code" (decimal strings)
 *   },
 *   "macros": [                  // optional, key-sequence macros
 *     {
 *       "trigger": { "modifiers": 64, "keycode": 4, "mod_mask": 64 },
 *       "steps": [
 *         { "modifier": 4, "keys": [98], "delay_us": 15000 },
 *         ...
 *       ]
 *     }
 *   ]
 * }
 */
bool load_keymap_from_json(const std::string& path) {
    std::ifstream file(path);
    if (!file.is_open()) {
        std::cerr << "Error: cannot open config file: " << path << std::endl;
        return false;
    }

    json j;
    try {
        file >> j;
    } catch (const std::exception& e) {
        std::cerr << "Error parsing JSON: " << e.what() << std::endl;
        return false;
    }

    // --- Load keycode_map ---
    if (j.contains("keycode_map")) {
        auto& km = j["keycode_map"];
        for (auto it = km.begin(); it != km.end(); ++it) {
            int from_code = std::stoi(it.key(), nullptr, 0);
            if (it.value().is_null()) {
                keycode_map[from_code] = 0;  // null = pass-through
            } else {
                keycode_map[from_code] = static_cast<uint8_t>(
                    std::stoi(it.value().get<std::string>(), nullptr, 0));
            }
        }
    }

    // --- Load macros ---
    if (j.contains("macros")) {
        for (const auto& m : j["macros"]) {
            uint8_t trig_mod = m["trigger"]["modifiers"].get<int>();
            uint8_t trig_key = m["trigger"]["keycode"].get<int>();
            uint8_t mod_mask = m["trigger"].value("mod_mask", 0xFF);

            std::vector<MacroStep> steps;
            for (const auto& s : m["steps"]) {
                MacroStep step;
                step.modifier = s["modifier"].get<int>();
                memset(step.keys, 0, 6);
                if (s.contains("keys")) {
                    int idx = 0;
                    for (const auto& k : s["keys"]) {
                        if (idx < 6) step.keys[idx++] = k.get<int>();
                    }
                }
                step.delay_us = s.value("delay_us", 0);
                steps.push_back(step);
            }

            add_macro(trig_mod, trig_key, mod_mask, std::move(steps));
        }
    }

    if (j.contains("description")) {
        std::cout << "Config: " << j["description"].get<std::string>() << std::endl;
    }
    std::cout << "Loaded config from " << path << ": "
              << macros.size() << " macros" << std::endl;
    return true;
}
/* End of AI generated block */


/*
 * AI generated by GitHub Copilot - DeepSeek V4 Flash
 *
 * Build an Alt+numpad HID report sequence for a given decimal code.
 * Returns a vector of MacroSteps.
 *
 * Example: code=224 produces steps for Alt+0224 (à).
 */
static std::vector<MacroStep> build_alt_numpad_sequence(int decimal_code) {
    // Digits of the decimal code (e.g. 224 -> {2, 2, 4})
    int digits[8];
    int digit_count = 0;
    int tmp = decimal_code;
    while (tmp > 0) {
        digits[digit_count++] = tmp % 10;
        tmp /= 10;
    }
    // Reverse to get most-significant first
    for (int i = 0; i < digit_count / 2; i++) {
        int t = digits[i];
        digits[i] = digits[digit_count - 1 - i];
        digits[digit_count - 1 - i] = t;
    }

    // Numpad HID keycodes for digits 0-9
    static const uint8_t numpad_keys[] = {
        0x62, 0x59, 0x5A, 0x5B, 0x5C, 0x5D, 0x5E, 0x5F, 0x60, 0x61
    };

    std::vector<MacroStep> steps;

    // Step: Press LeftAlt alone
    MacroStep s;
    s.modifier = 0x04;
    memset(s.keys, 0, 6);
    s.delay_us = 20000;
    steps.push_back(s);

    // Steps for each digit: press numpad key, then release
    for (int d = 0; d < digit_count; d++) {
        MacroStep press;
        press.modifier = 0x04;
        memset(press.keys, 0, 6);
        press.keys[0] = numpad_keys[digits[d]];
        press.delay_us = 15000;
        steps.push_back(press);

        MacroStep release;
        release.modifier = 0x04;
        memset(release.keys, 0, 6);
        release.delay_us = 10000;
        steps.push_back(release);
    }

    // Final step: release LeftAlt
    MacroStep finish;
    finish.modifier = 0x00;
    memset(finish.keys, 0, 6);
    finish.delay_us = 0;
    steps.push_back(finish);

    return steps;
}


/*
 * AI generated by GitHub Copilot - DeepSeek V4 Flash
 *
 * Register macros for an accented character with proper modifier masking.
 *
 * For AltGr variants (no Shift):  trigger_mod=0x40, mod_mask=0x40
 * For AltGr+Shift variants:       trigger_mod=0x42, mod_mask=0x42
 *
 * Shift-requiring macros are registered FIRST so they are checked
 * before the unshifted variant. This ensures AltGr+Shift+E matches
 * é (requires Shift) instead of è (matches without Shift).
 *
 * Each variant is registered twice: once for RightAlt (0x40) and
 * once for LeftAlt (0x04), to support different keyboard types.
 */

struct CharMap {
    uint8_t key;       // HID keycode
    int  alt_code;     // Windows Alt+numpad decimal code
    bool need_shift;   // true = requires Shift, false = no Shift
};

static void register_char_macros(const CharMap& ch) {
    auto steps = build_alt_numpad_sequence(ch.alt_code);
    if (steps.empty()) return;

    uint8_t mod = ch.need_shift ? 0x42 : 0x40;
    uint8_t mask = ch.need_shift ? 0x42 : 0x40;

    add_macro(mod, ch.key, mask, steps);                    // RightAlt (+ Shift)
    add_macro(mod & ~0x40 | 0x04, ch.key, mask & ~0x40 | 0x04,
              std::move(steps));                             // LeftAlt (+ Shift)
}


void load_keymap_italian() {
    // --- Approach: Host-side Italian layout + raw forwarding ---
    //
    // This config expects the HOST PC to have its keyboard layout set
    // to Italian.  The Pi forwards RAW HID scan codes (no remapping)
    // so that each physical key position produces the character that
    // an Italian keyboard would have at that position.
    //
    // On the Pi 500's UK keyboard, the Italian characters appear at:
    //   [è] at the [ key      [ò] at the ; key      [à] at the ' key
    //   [ù] at the \ key      [ì] at the = key      [é] at Shift+[
    //
    // Keycode_map is all-zeros (identity) — raw pass-through.
    //
    // --- Macros for chars NOT on standard Italian layout ---
    // Characters like ç, ê, ë, ï, ñ, ô, ö, û, ü, ÿ require AltGr or
    // compose sequences on ANY standard layout.  The AltGr macros below
    // inject Alt+numpad codes so they work when the host is Windows.

    // Chars that need AltGr even on a real Italian keyboard:
    // ç, ê, ë, ï, ñ, ô, ö, û, ü, ÿ
    // Also uppercase variants: Ç, Ê, Ë, Ï, Ñ, Ô, Ö, Û, Ü, Ÿ

    // Extended chars mapped to letter keys via AltGr:
    // AltGr + C → ç (231)    AltGr+Shift + C → Ç (199)
    // AltGr + E → ê (234)    AltGr+Shift + E → Ê (202)
    // AltGr + I → ï (239)    AltGr+Shift + I → Ï (207)
    // AltGr + N → ñ (241)    AltGr+Shift + N → Ñ (209)
    // AltGr + O → ô (244)    AltGr+Shift + O → Ô (212)
    // AltGr + R → ë (235)    AltGr+Shift + R → Ë (203)
    // AltGr + U → û (251)    AltGr+Shift + U → Û (219)
    // AltGr + Y → ü (252)    AltGr+Shift + Y → Ü (220)
    // AltGr + Shift + ? → Ÿ (159) on ... key

    // Note: è, é, à, ò, ù, ì are NOT registered as macros because they
    // are directly available via Italian host layout with raw forwarding.
    // Remove this line to also register them as AltGr macros.

    struct { uint8_t key; int code; bool shift; } extended[] = {
        {0x06, 231, false},  // C → ç
        {0x06, 199, true},   // C+Shift → Ç
        {0x08, 234, false},  // E → ê
        {0x08, 202, true},   // E+Shift → Ê
        {0x0A, 239, false},  // I → ï
        {0x0A, 207, true},   // I+Shift → Ï
        {0x11, 241, false},  // N → ñ
        {0x11, 209, true},   // N+Shift → Ñ
        {0x12, 244, false},  // O → ô
        {0x12, 212, true},   // O+Shift → Ô
        {0x13, 235, false},  // R → ë
        {0x13, 203, true},   // R+Shift → Ë
        {0x15, 251, false},  // U → û
        {0x15, 219, true},   // U+Shift → Û
        {0x1A, 252, false},  // Y → ü
        {0x1A, 220, true},   // Y+Shift → Ü
    };

    for (auto& ch : extended) {
        CharMap cm = {ch.key, ch.code, ch.shift};
        register_char_macros(cm);
    }

    std::cout << "Loaded Italian layout: raw forwarding + "
              << macros.size() << " AltGr macros for extended chars"
              << std::endl;
    std::cout << "  Set host PC keyboard layout to Italian for best results." << std::endl;
    std::cout << "  UK physical positions: [=è  ;=ò  '=à  \\=ù  ==ì  Shift+[=é" << std::endl;
    std::cout << "  AltGr+C=ç  AltGr+E=ê  AltGr+I=ï  AltGr+N=ñ" << std::endl;
    std::cout << "  AltGr+O=ô  AltGr+R=ë  AltGr+U=û  AltGr+Y=ü" << std::endl;
}
/* End of AI generated block */
