/*
 * AI generated by GitHub Copilot - DeepSeek V4 Flash
 *
 * keyqueue.h — Thread-safe key event queue for keyboard macro/mapping support.
 */
#ifndef KEYQUEUE_H
#define KEYQUEUE_H

#include <queue>
#include <mutex>
#include <vector>
#include <string>
#include <cstdint>
#include <cstddef>

#define KEYBOARD_HID_REPORT_SIZE 8

/*
 * AI generated by GitHub Copilot - DeepSeek V4 Flash
 *
 * KeyEvent: Represents a single key transition (press or release)
 * Used by the keyboard macro/mapping queue system.
 */
struct KeyEvent {
    uint8_t modifiers;  // modifier byte (Ctrl=0x01, Shift=0x02, Alt=0x04, GUI=0x08)
    uint8_t keycode;    // HID usage code (0x00 = no key)
    bool    pressed;    // true = key down, false = key up
};
/* End of AI generated block */


/*
 * AI generated by GitHub Copilot - DeepSeek V4 Flash
 *
 * KeyQueue: Thread-safe FIFO queue for keyboard events.
 * Enables macro injection and key remapping by decoupling
 * HID report reading from USB gadget output writing.
 */
class KeyQueue {
    std::queue<KeyEvent> queue_;
    mutable std::mutex mutex_;
public:
    void push(const KeyEvent& ev);
    bool pop(KeyEvent& ev);
    void clear();
    bool empty() const;
    size_t size() const;
};
/* End of AI generated block */


/*
 * AI generated by GitHub Copilot - DeepSeek V4 Flash
 *
 * Default (identity) key mapping table.
 * keycode_map[from] = to  — replace this with a populated map
 * for custom layouts (e.g. Italian → German).
 * A value of 0 means pass-through (no mapping).
 */
extern uint8_t keycode_map[256];
/* End of AI generated block */


/*
 * AI generated by GitHub Copilot - DeepSeek V4 Flash
 *
 * Macro system for key-sequence injection (e.g. Alt+numpad codes).
 * Uses std::vector for dynamic macro storage.
 */

/*
 * One step in a macro sequence = one complete HID report to send.
 */
struct MacroStep {
    uint8_t modifier;       // modifier byte for this step
    uint8_t keys[6];        // up to 6 keycodes (remaining bytes zero)
    int delay_us;           // pause after this step (microseconds)
};

/*
 * A macro: triggers when a specific key is pressed while specific
 * modifiers are held. Executes a multi-step HID report sequence.
 *   trigger_mod  - modifier bits that must be set
 *   mod_mask     - which bits to compare (e.g. 0x40 = check only RightAlt)
 *   trigger_key  - keycode that fires the macro (0 = any key with those mods)
 */
struct Macro {
    uint8_t trigger_mod;
    uint8_t trigger_key;
    uint8_t mod_mask;
    std::vector<MacroStep> steps;
};

extern std::vector<Macro> macros;

// Add a macro definition. Returns index or -1 on failure.
int add_macro(uint8_t trigger_mod, uint8_t trigger_key, uint8_t mod_mask,
              std::vector<MacroStep> steps);

// Check raw HID reports for macro triggers.
// If triggered: writes the macro sequence to hid_output_fd and returns true.
bool check_and_execute_macro(const unsigned char* old_report,
                              const unsigned char* new_report,
                              int hid_output_fd);

// Load a keyboard layout from a JSON config file.
// Returns true on success.
// The JSON file uses decimal integers for HID codes.
bool load_keymap_from_json(const std::string& path);

// Built-in Italian keyboard layout (keycode_map + AltGr+numpad macros)
void load_keymap_italian();
/* End of AI generated block */


/*
 * AI generated by GitHub Copilot - DeepSeek V4 Flash
 *
 * Utility functions for HID report diffing and queue processing.
 */

// Diff two HID reports and push individual KeyEvents into the queue.
void diff_hid_reports(const unsigned char* old_report,
                      const unsigned char* new_report,
                      KeyQueue& queue);

// Build a modifier byte from held modifier keycodes.
uint8_t modifiers_from_held(const bool held_keys[256]);

// Process a queue of KeyEvents into an output HID report (8 bytes).
void process_key_queue(KeyQueue& queue,
                       unsigned char* out_report,
                       bool is_grabbed);
/* End of AI generated block */

#endif /* KEYQUEUE_H */
