#!/usr/bin/env bash
#
# make.sh - Configure and build the pi500kb project
#
# AI generated by GitHub Copilot v1.0
# End of AI generated code

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="${SCRIPT_DIR}/build"

# Create build directory if it doesn't exist
if [ ! -d "${BUILD_DIR}" ]; then
    echo "Creating build directory..."
    mkdir -p "${BUILD_DIR}"
fi

# Configure
echo "Configuring project..."
cd "${BUILD_DIR}"
cmake "${SCRIPT_DIR}" \
    -DKEYBOARD_VID=0x2e8a \
    -DKEYBOARD_PID=0x0010 \
    -DKEYBOARD_DEV=/dev/input/by-id/usb-Raspberry_Pi_Ltd_Pi_500_Keyboard-event-kbd

# Build
echo "Building project..."
cmake --build "${BUILD_DIR}" -j "$(nproc)"

echo ""
echo "Build complete! Binary at: ${BUILD_DIR}/pi500kb"
