#include "pi500.h"
#include "keyqueue.h"

#include "gadget-hid.h"

#include <sys/ioctl.h>
#include <linux/hidraw.h>
#include <linux/input.h>
#include <signal.h>
#include <cerrno>
#include <cstdio>
#include <fcntl.h>
#include <poll.h>
#include <unistd.h>
#include <cstring>
#include <cstdlib>
#include <sys/types.h>
#include <sys/wait.h>

#include <iostream>
#include <fstream>
#include <format>
#include <string>
#include <string_view>
#include <vector>
#include <set>
#include <atomic>
#include <thread>
#include <chrono>


struct KeyboardDevice {
    int hidraw_fd = -1;      // /dev/hidrawX for reading HID reports
    int uinput_fd = -1;      // Grabbed evdev fd (returned by grab())
    struct hid_buf buf{};    // HID report buffer
    unsigned char prev_data[KEYBOARD_HID_REPORT_SIZE]{}; // Previous report for diffing
    std::string evdev_path;  // evdev device path (for grab/ungrab)
    std::string name;        // Display name for logging
};

constexpr int EVIOC_GRAB = 1;
constexpr int EVIOC_UNGRAB = 0;

int hid_output;
std::atomic<bool> running{false};
std::atomic<bool> grabbed{false};

int ret;
std::vector<KeyboardDevice> keyboards;
int mouse_fd;
int uinput_mouse_fd;
struct hid_buf mouse_buf;

static bool keyboard_only = false;
std::string hook_path = HOOK_PATH;

/*
 * AI generated by GitHub Copilot - DeepSeek V4 Flash
 * Global key event queue for macro/mapping support.
 */
KeyQueue key_queue;
/* End of AI generated block */

void signal_handler(int /*dummy*/) {
    running = false;
}

bool modprobe_libcomposite() {
    pid_t pid;

    pid = fork();

    if (pid < 0) return false;
    if (pid == 0) {
        const char* const argv[] = {"modprobe", "libcomposite", nullptr};
        execv("/usr/sbin/modprobe", const_cast<char *const *>(argv));
        std::exit(0);
    }
    waitpid(pid, nullptr, 0);
    return true;
}

bool trigger_hook() {
    if (hook_path.empty()) return false;
    auto cmd = std::format("{} {}", hook_path, grabbed.load() ? 1u : 0u);
    std::system(cmd.c_str());
    return true;
}

int find_hidraw_device(const char *device_type, int16_t vid, int16_t pid) {
    struct hidraw_devinfo hidinfo;

    for(int x = 0; x < 16; x++){
        auto path = std::format("/dev/hidraw{}", x);

        int fd = open(path.c_str(), O_RDWR | O_NONBLOCK);
        if (fd == -1) {
            continue;
        }

        if (ioctl(fd, HIDIOCGRAWINFO, &hidinfo) == 0 &&
            hidinfo.vendor == vid && hidinfo.product == pid) {
            std::cout << "Found " << device_type << " at: " << path << std::endl;
            return fd;
        }

        close(fd);
    }

    return -1;
}

/*
 * Find the /dev/hidrawN path that matches an evdev device's VID/PID.
 * Returns empty string if no match found.
 */
std::string find_hidraw_path_for_evdev(const char *evdev_path) {
    int tmp_fd = open(evdev_path, O_RDONLY);
    if (tmp_fd == -1) return "";

    struct input_id ids{};
    int ret_io = ioctl(tmp_fd, EVIOCGID, &ids);
    close(tmp_fd);

    if (ret_io == -1) return "";

    struct hidraw_devinfo hidinfo;
    for (int x = 0; x < 16; x++) {
        auto path = std::format("/dev/hidraw{}", x);
        int fd = open(path.c_str(), O_RDWR | O_NONBLOCK);
        if (fd == -1) continue;

        if (ioctl(fd, HIDIOCGRAWINFO, &hidinfo) == 0 &&
            hidinfo.vendor == ids.vendor && hidinfo.product == ids.product) {
            close(fd);
            return path;
        }
        close(fd);
    }
    return "";
}

std::vector<std::string> discover_all_keyboards() {
    std::vector<std::string> paths;
    char devname[256] = {};

    for (int i = 0; i < 32; i++) {
        auto path = std::format("/dev/input/event{}", i);
        int fd = open(path.c_str(), O_RDONLY);
        if (fd == -1) continue;

        if (ioctl(fd, EVIOCGNAME(sizeof(devname)), devname) >= 0) {
            std::string name(devname);
            /* Look for keyboard-like device names, skip mice */
            bool is_kb = (name.find("Keyboard") != std::string::npos ||
                          name.find("keyboard") != std::string::npos ||
                          name.find("kbd") != std::string::npos);
            bool is_mouse = (name.find("Mouse") != std::string::npos ||
                             name.find("mouse") != std::string::npos);

            /* Skip the gadget's own HID device (creates feedback loops) */
            bool is_gadget = (name.find("Pi400") != std::string::npos ||
                              name.find("pi400") != std::string::npos ||
                              name.find("Pi500") != std::string::npos ||
                              name.find("pi500") != std::string::npos);

            /* Skip subsystems that aren't real keyboards */
            bool is_subsystem = (name.find("Sleep") != std::string::npos ||
                                 name.find("Power") != std::string::npos ||
                                 name.find("Video") != std::string::npos);

            if (is_kb && !is_mouse && !is_gadget && !is_subsystem) {
                paths.push_back(path);
            }
        }
        close(fd);
    }
    return paths;
}

int grab(const char *dev) {
    std::cout << "Grabbing: " << dev << std::endl;
    int fd = open(dev, O_RDONLY);
    ioctl(fd, EVIOCGRAB, EVIOC_UNGRAB);
    std::this_thread::sleep_for(std::chrono::milliseconds(500));
    ioctl(fd, EVIOCGRAB, EVIOC_GRAB);
    return fd;
}

void ungrab(int fd) {
    ioctl(fd, EVIOCGRAB, EVIOC_UNGRAB);
    close(fd);
}

void print_usage(const char *prog) {
    std::cout << std::format(
        "Usage: {} [OPTIONS]\n"
        "\n"
        "Forward the Pi 500's keyboard (and optionally mouse) to a host PC\n"
        "via USB HID gadget.\n"
        "\n"
        "Keyboard selection (default: built-in only):\n"
        "  --keyboard <path>       Forward a specific keyboard by evdev path\n"
        "                          (can be specified multiple times)\n"
        "  --all-keyboards         Auto-discover and forward all keyboards\n"
        "\n"
        "Layout & macro options:\n"
        "  --host-os <os>          Host operating system for macro sequences:\n"
        "                            windows  - use Alt+numpad codes (default)\n"
        "                            linux    - use Ctrl+Shift+U Unicode sequences\n"
        "  --config <path>         Path to keyboard layout JSON config file\n"
        "                          (default: built-in Italian layout)\n"
        "\n"
        "Other options:\n"
        "  -k, --keyboard-only     Skip mouse detection\n"
        "  --hook-path <path>      Path to shell hook script called on\n"
        "                          grab/release (default: " HOOK_PATH ")\n"
        "  -h, --help              Show this help message and exit\n"
        "\n"
        "Key bindings (when running):\n"
        "  Ctrl + Raspberry        Toggle grab/release (Pi keyboard vs host)\n"
        "  Ctrl + Shift + Raspberry  Exit the program\n",
        prog);
}

void printhex(unsigned char *buf, size_t len) {
    for(size_t x = 0; x < len; x++) {
        std::cout << std::format("{:x} ", buf[x]);
    }
    std::cout << std::endl;
}

void ungrab_both() {
    std::cout << "Releasing Keyboards and/or Mouse" << std::endl;

    for (auto& kb : keyboards) {
        if(kb.uinput_fd > -1) {
            ungrab(kb.uinput_fd);
            kb.uinput_fd = -1;
        }
        // Reset previous state so we don't carry stale data
        memset(kb.prev_data, 0, KEYBOARD_HID_REPORT_SIZE);
    }

    if(uinput_mouse_fd > -1) {
        ungrab(uinput_mouse_fd);
        uinput_mouse_fd = -1;
    }

    grabbed = false;
    key_queue.clear();

    trigger_hook();
}

void grab_both() {
    std::cout << "Grabbing Keyboards and/or Mouse" << std::endl;

    for (auto& kb : keyboards) {
        kb.uinput_fd = grab(kb.evdev_path.c_str());
        // Clear previous state so we start fresh
        memset(kb.prev_data, 0, KEYBOARD_HID_REPORT_SIZE);
    }

    if(mouse_fd > -1) {
        uinput_mouse_fd = grab(MOUSE_DEV);
    }

    if (!keyboards.empty() || uinput_mouse_fd > -1) {
        grabbed = true;
    }

    key_queue.clear();

    trigger_hook();
}

void send_empty_hid_reports_both() {
#ifndef NO_OUTPUT
    for (auto& kb : keyboards) {
        kb.buf = {};
        write(hid_output, reinterpret_cast<unsigned char *>(&kb.buf), KEYBOARD_HID_REPORT_SIZE + 1);
    }

    if(mouse_fd > -1) {
        mouse_buf = {};
        write(hid_output, reinterpret_cast<unsigned char *>(&mouse_buf), MOUSE_HID_REPORT_SIZE + 1);
    }
#endif
}

int main(int argc, char *argv[]) {
    /* Parse command line arguments */
    std::vector<std::string> keyboard_paths;
    bool all_keyboards = false;
    std::string host_os = "windows";
    std::string config_path;

    for (int i = 1; i < argc; i++) {
        std::string_view arg{argv[i]};
        if (arg == "-h" || arg == "--help") {
            print_usage(argv[0]);
            return 0;
        } else if (arg == "-k" || arg == "--keyboard-only") {
            keyboard_only = true;
        } else if (arg == "--all-keyboards") {
            all_keyboards = true;
        } else if (arg == "--hook-path" && i + 1 < argc) {
            hook_path = argv[++i];
        } else if (arg == "--keyboard" && i + 1 < argc) {
            keyboard_paths.emplace_back(argv[++i]);
        } else if (arg == "--host-os" && i + 1 < argc) {
            host_os = argv[++i];
        } else if (arg == "--config" && i + 1 < argc) {
            config_path = argv[++i];
        }
    }

    modprobe_libcomposite();

    /*
     * AI generated by GitHub Copilot - DeepSeek V4 Flash
     * Load keyboard layout — from JSON config file or built-in Italian.
     * Host OS setting selects the macro injection method.
     */
    if (!config_path.empty()) {
        if (!load_keymap_from_json(config_path)) {
            std::cerr << "Failed to load config, falling back to built-in Italian layout" << std::endl;
            load_keymap_italian();
        }
    } else {
        load_keymap_italian();
    }

    if (host_os == "linux") {
        std::cout << "Host OS: Linux — Ctrl+Shift+U compose not yet implemented, host layout method recommended" << std::endl;
    } else {
        std::cout << "Host OS: Windows — AltGr macros use Alt+numpad sequences" << std::endl;
    }
    /* End of AI generated block */

    mouse_buf.report_id = 2;

    /* Determine which keyboards to forward */
    if (all_keyboards) {
        keyboard_paths = discover_all_keyboards();
        std::cout << "Discovered " << keyboard_paths.size() << " keyboard(s)" << std::endl;
    }

    if (!keyboard_paths.empty()) {
        /* Deduplicate by hidraw PATH (not fd — multiple opens of the same
         * /dev/hidrawN return different fd numbers). */
        std::set<std::string> seen_hidraw_paths;
        for (const auto& ev_path : keyboard_paths) {
            auto hd_path = find_hidraw_path_for_evdev(ev_path.c_str());
            if (hd_path.empty()) {
                std::cout << "No hidraw device found for: " << ev_path << std::endl;
                continue;
            }
            if (seen_hidraw_paths.count(hd_path)) {
                continue;  // already have this hidraw device
            }
            seen_hidraw_paths.insert(hd_path);

            int hd_fd = open(hd_path.c_str(), O_RDWR | O_NONBLOCK);
            if (hd_fd == -1) continue;

            std::cout << "Found keyboard at: " << hd_path << std::endl;

            KeyboardDevice kb;
            kb.hidraw_fd = hd_fd;
            kb.evdev_path = ev_path;
            kb.buf.report_id = 1;
            kb.name = hd_path;
            keyboards.push_back(kb);
        }
    } else {
        /* Default: use the built-in keyboard */
        int hd_fd = find_hidraw_device("keyboard", KEYBOARD_VID, KEYBOARD_PID);
        if (hd_fd == -1) {
            std::cout << "Failed to open built-in keyboard device" << std::endl;
        } else {
            KeyboardDevice kb;
            kb.hidraw_fd = hd_fd;
            kb.evdev_path = KEYBOARD_DEV;
            kb.buf.report_id = 1;
            kb.name = "built-in";
            keyboards.push_back(kb);
        }
    }
    
    if (!keyboard_only) {
        mouse_fd = find_hidraw_device("mouse", MOUSE_VID, MOUSE_PID);
        if(mouse_fd == -1) {
            std::cout << "No mouse device found (keyboard-only mode)" << std::endl;
        }
    } else {
        mouse_fd = -1;
        std::cout << "Mouse disabled (--keyboard-only)" << std::endl;
    }

    if(mouse_fd == -1 && keyboards.empty()) {
        std::cout << "No devices to forward, bailing out!" << std::endl;
        return 1;
    }

#ifndef NO_OUTPUT
    ret = initUSB();
    if(ret != USBG_SUCCESS && ret != USBG_ERROR_EXIST) {
        return 1;
    }

    /* Check UDC state — should be 'configured' when host is connected */
    {
        std::ifstream udc_state("/sys/class/udc/1000480000.usb/state");
        if (udc_state.is_open()) {
            std::string state;
            udc_state >> state;
            std::cout << "UDC state: " << state;
            if (state != "configured") {
                std::cout << " — host may not be connected!" << std::endl;
                std::cout << "Try unplugging/replugging the USB cable." << std::endl;
            } else {
                std::cout << " — host connected" << std::endl;
            }
        }
    }
#endif

    grab_both();


#ifndef NO_OUTPUT
    /* Find the first available /dev/hidg* device */
    do {
        for (int i = 0; i < 16; i++) {
            auto devpath = std::format("/dev/hidg{}", i);
            hid_output = open(devpath.c_str(), O_WRONLY | O_NDELAY);
            if (hid_output != -1) {
                std::cout << "Opened " << devpath << " for output" << std::endl;
                break;
            }
        }
    } while (hid_output == -1 && errno == EINTR);

    if (hid_output == -1){
        std::cout << "Error opening /dev/hidg* for writing." << std::endl;
        return 1;
    }
#endif

    std::cout << "Running..." << std::endl;
    running = true;
    signal(SIGINT, signal_handler);

    /* Build pollfd array: all keyboards + mouse */
    std::vector<struct pollfd> pollFd;
    for (auto& kb : keyboards) {
        pollFd.push_back({kb.hidraw_fd, POLLIN, 0});
    }
    pollFd.push_back({mouse_fd, POLLIN, 0});

    while (running.load()){
        poll(pollFd.data(), pollFd.size(), -1);

        /* Process all keyboards */
        for (size_t ki = 0; ki < keyboards.size(); ki++) {
            if (!(pollFd[ki].revents & POLLIN)) continue;

            auto& kb = keyboards[ki];
            auto c = read(kb.hidraw_fd, kb.buf.data, KEYBOARD_HID_REPORT_SIZE);

            if(c == KEYBOARD_HID_REPORT_SIZE){
                std::cout << "K(" << kb.name << "):";
                printhex(kb.buf.data, KEYBOARD_HID_REPORT_SIZE);

                /*
                 * AI generated by GitHub Copilot - DeepSeek V4 Flash
                 * Step 1: Check for macro triggers.
                 * If a macro fires, it writes the Alt+numpad sequence directly
                 * to /dev/hidg0 and we skip normal forwarding.
                 */
#ifndef NO_OUTPUT
                if(grabbed.load()) {
                    /* Debug: show modifier state whenever it changes */
                    uint8_t mod_change = kb.buf.data[0] ^ kb.prev_data[0];
                    if (mod_change) {
                        std::cout << "  *** Modifier: 0x"
                                  << std::format("{:02x}", kb.buf.data[0])
                                  << " (was 0x" << std::format("{:02x}", kb.prev_data[0])
                                  << ")" << std::endl;
                    }
                    if (check_and_execute_macro(kb.prev_data, kb.buf.data, hid_output)) {
                        std::cout << "  -> Macro triggered" << std::endl;
                        memcpy(kb.prev_data, kb.buf.data, KEYBOARD_HID_REPORT_SIZE);
                        goto macro_skip;
                    }
                }
#endif
                /* End of AI generated block */

                /*
                 * AI generated by GitHub Copilot - DeepSeek V4 Flash
                 * Step 2: Forward raw HID report with keycode remapping.
                 *
                 * The raw report already represents the complete key state
                 * (modifier byte + up to 6 keycodes). We apply keycode_map
                 * remapping to each keycode byte, then write it to /dev/hidg0.
                 *
                 * This is correct because USB HID uses state-based reports,
                 * not event-based. The old queue-based approach (diff_hid_reports
                 * + process_key_queue) lost state between iterations — held keys
                 * were only reported once then dropped.
                 */
                unsigned char out_report[KEYBOARD_HID_REPORT_SIZE];
                memcpy(out_report, kb.buf.data, KEYBOARD_HID_REPORT_SIZE);

                // Apply keycode_map remapping to keycodes (bytes 2-7)
                for (int i = 2; i < KEYBOARD_HID_REPORT_SIZE; i++) {
                    uint8_t mapped = keycode_map[out_report[i]];
                    if (mapped != 0) {
                        out_report[i] = mapped;
                    }
                }

#ifndef NO_OUTPUT
                if(grabbed.load()) {
                    struct hid_buf out_buf;
                    out_buf.report_id = 1;
                    memcpy(out_buf.data, out_report, KEYBOARD_HID_REPORT_SIZE);
                    // Retry on EAGAIN — USB endpoint may be busy
                    int retries = 20;
                    while (retries-- > 0) {
                        ssize_t wr = write(hid_output, reinterpret_cast<unsigned char *>(&out_buf),
                                           KEYBOARD_HID_REPORT_SIZE + 1);
                        if (wr >= 0) break;
                        if (errno == EAGAIN) {
                            usleep(1000);
                        } else {
                            std::cout << "  -> write failed: " << strerror(errno) << std::endl;
                            break;
                        }
                    }
                    std::this_thread::sleep_for(std::chrono::microseconds(1000));
                }
#endif

                // Update prev_data for next iteration's macro/remap diff
                memcpy(kb.prev_data, kb.buf.data, KEYBOARD_HID_REPORT_SIZE);
                /* End of AI generated block */

macro_skip:

                // Trap Ctrl + Raspberry and toggle capture on/off
                // Check on all keyboards (only built-in has the Raspberry key)
                if(kb.buf.data[0] == 0x09){
                    if(grabbed.load()) {
                        ungrab_both();
                        send_empty_hid_reports_both();
                    } else {
                        grab_both();
                    }
                }
                // Trap Ctrl + Shift + Raspberry and exit
                if(kb.buf.data[0] == 0x0b){
                    running = false;
                    break;
                }
            }
        }
        if (!running.load()) break;

        /* Process mouse (last entry in pollFd) */
        size_t mouse_idx = keyboards.size();
        if (mouse_fd > -1 && (pollFd[mouse_idx].revents & POLLIN)) {
            mouse_buf = {};
            auto c = read(mouse_fd, mouse_buf.data, MOUSE_HID_REPORT_SIZE);

            if(c == MOUSE_HID_REPORT_SIZE){
                std::cout << "M:";
                printhex(mouse_buf.data, MOUSE_HID_REPORT_SIZE);

#ifndef NO_OUTPUT
                if(grabbed.load()) {
                    write(hid_output, reinterpret_cast<unsigned char *>(&mouse_buf), MOUSE_HID_REPORT_SIZE + 1);
                    std::this_thread::sleep_for(std::chrono::microseconds(1000));
                }
#endif
            }
        }
    }

    ungrab_both();
    send_empty_hid_reports_both();

#ifndef NO_OUTPUT
    std::cout << "Cleanup USB" << std::endl;
    cleanupUSB();
#endif

    return 0;
}
